namespace: stackhpc
name: linux
version: 1.0.0
readme: README.md
authors:
  - Mark Goddard <mark@stackhpc.com>
description: Ansible collection for configuring linux based operating systems
license:
  - "Apache-2.0"
tags:
  - linux
dependencies: {}
repository: https://github.com/stackhpc/ansible-collection-linux
documentation: https://github.com/stackhpc/ansible-collection-linux/branch/master/README.md
homepage: https://github.com/stackhpc/ansible-collection-linux
issues: https://github.com/stackhpc/ansible-collection-linux/issues
build_ignore:
  - "*.tar.gz"
  - .gitignore
