---
- name: Include gpu-facts.yml
  ansible.builtin.include_tasks:
    file: gpu-facts.yml
  loop: "{{ vgpu_definitions }}"
  loop_control:
    loop_var: vgpu_definition

- name: Show card index
  ansible.builtin.debug:
    var: vgpu_card_index

- name: Include configure-mig.yml
  ansible.builtin.include_tasks:
    file: configure-mig.yml
  when: vgpu_mig_enabled | bool

- name: Template udev rule to tag systemd device
  ansible.builtin.template:
    src: udev.rule.j2
    dest: /etc/udev/rules.d/50-nvidia-systemd.rules
    owner: root
    group: root
    mode: "664"
  become: true

- name: Include configure-gpu.yml
  ansible.builtin.include_tasks:
    file: configure-gpu.yml
  loop: "{{ vgpu_definitions }}"
  loop_control:
    loop_var: vgpu_definition
