---
- name: Include validate.yml
  ansible.builtin.include_tasks:
    file: validate.yml
  when: vgpu_definitions | length > 0

- name: Include install.yml
  ansible.builtin.include_tasks:
    file: install.yml
  when: vgpu_definitions | length > 0

- name: Include configure.yml
  ansible.builtin.include_tasks:
    file: configure.yml
  when: vgpu_definitions | length > 0
