---

- include_tasks:
    file: validate.yml
  when: vgpu_definitions | length > 0

- include_tasks:
    file: install.yml
  when: vgpu_definitions | length > 0

- include_tasks:
    file: configure.yml
  when: vgpu_definitions | length > 0
