#!/bin/bash

. /etc/init.d/functions

cd /etc/sysconfig/network-scripts
. ./network-functions

[ -f ../network ] && . ../network

CONFIG=${1}

need_config ${CONFIG}

source_config

/etc/sysconfig/network-scripts/ifdown-eth ${CONFIG}
/etc/sysconfig/network-scripts/ifdown-post ${CONFIG}