---
# handlers for ansible-role-systemd-resolved

- name: Restart systemd-resolved
  become: true
  ansible.builtin.service:
    name: systemd-resolved
    state: restarted

- name: Restart NetworkManager
  become: true
  ansible.builtin.service:
    name: NetworkManager
    state: restarted
