---
# Whether to install the nvidia driver. Set to false if you want to install the driver
# via some other means.
vgpu_nvidia_driver_install_enabled: true
vgpu_driver_url: ""
vgpu_driver_force_install: false
vgpu_driver_dkms: false
vgpu_do_reboot: true
vgpu_reboot_timeout: 3600

# Time in seconds to sleep before enabling sriov
vgpu_sriov_init_delay: 30

# Deprecated: use vgpu_definitions instead.
vgpu_mig_definitions: []
vgpu_definitions: "{{ vgpu_mig_definitions }}"

# Whether to enable MIG support. This is required when using MIG.
vgpu_mig_enabled: "{{ vgpu_definitions | selectattr('mig_devices', 'defined') | length > 0 }}"

# Packages providing nvidia-mig-manager
vgpu_nvidia_mig_manager_rpm_url: https://github.com/NVIDIA/mig-parted/releases/download/v0.12.1/nvidia-mig-manager-0.12.1-1.x86_64.rpm
vgpu_nvidia_mig_manager_deb_url: https://github.com/NVIDIA/mig-parted/releases/download/v0.12.1/nvidia-mig-manager_0.12.1-1_amd64.deb
