---
vgpu_driver_url: ""
vgpu_driver_force_install: false
vgpu_driver_dkms: false
vgpu_do_reboot: true
vgpu_reboot_timeout: 3600

# Deprecated: use vgpu_definitions instead.
vgpu_mig_definitions: []
vgpu_definitions: "{{ vgpu_mig_definitions }}"

# Packages providing nvidia-mig-manager
vgpu_nvidia_mig_manager_rpm_url: https://github.com/NVIDIA/mig-parted/releases/download/v0.5.1/nvidia-mig-manager-0.5.1-1.x86_64.rpm
vgpu_nvidia_mig_manager_deb_url: https://github.com/NVIDIA/mig-parted/releases/download/v0.5.1/nvidia-mig-manager_0.5.1-1_amd64.deb
