---
vgpu_driver_path: "{{ lookup('env', 'HOME') }}/NVIDIA-GRID-Linux-KVM-525.85.07-525.85.05-528.24.zip"
vgpu_driver_url: "file://{{ vgpu_driver_path }}"
vgpu_driver_force_install: false
vgpu_driver_dkms: false
# Deprecated: use vgpu_definitions instead.
vgpu_mig_definitions: []
vgpu_definitions: "{{ vgpu_mig_definitions }}"
