---

- name: Make sure systemd-resolved is installed
  become: true
  ansible.builtin.package:
    name: systemd-resolved
    state: present
  when:
    - ansible_facts.distribution | lower == 'debian'
    - ansible_facts.distribution_major_version >= '12'
    - ansible_facts.os_family == "RedHat"
    - ansible_facts.distribution_major_version | int >= 10

- name: Enable and configure systemd-resolved
  become: true
  when: systemd_resolved_enable_resolved is truthy
  block:
    - name: Create a NetworkManager/conf.d directory if it does not exist
      ansible.builtin.file:
        path: /etc/NetworkManager/conf.d/
        state: directory
        mode: '0755'
      when:
        - ansible_facts.os_family == "RedHat"
        - ansible_facts.distribution_major_version | int >= 10

    - name: Configure NetworkManager dns.conf to use systemd-resolved
      ansible.builtin.template:
        src: "nm_dns_config.j2"
        dest: "/etc/NetworkManager/conf.d/dns.conf"
        mode: "0644"
      notify:
        - Restart NetworkManager
      when:
        - ansible_facts.os_family == "RedHat"
        - ansible_facts.distribution_major_version | int >= 10

    - name: Create a resolved.conf.d directory if it does not exist
      ansible.builtin.file:
        path: /etc/systemd/resolved.conf.d/
        state: directory
        mode: '0755'

    - name: Configure dns.conf
      ansible.builtin.template:
        src: "dns_config.j2"
        dest: "/etc/systemd/resolved.conf.d/dns.conf"
        mode: "0644"
      notify:
        - Restart systemd-resolved

    - name: Start and enable systemd-resolved
      ansible.builtin.service:
        name: systemd-resolved
        enabled: true
        state: started

- name: Replace /etc/resolv.conf with a symlink to the systemd-resolved stub
  become: true
  ansible.builtin.file:
    path: /etc/resolv.conf
    src: /run/systemd/resolve/stub-resolv.conf
    state: link
    force: true
  when: systemd_resolved_symlink_resolv_conf | bool

# vim: set ts=2 sw=2:
